branches_to_handle:
  - master
  - develop
github:
  post_secret: GITHUB_POST_SECRET
codeship:
  api_key: CODESHIP_API_KEY
  project_id: 12345
  attempted_build_finds: 5  # optional -- defaults to 5
  wait_timeout: 1500        # optional -- defaults to 1500
slack:
  webhook_url: SLACK_WEBHOOK_URL
  username: SLACK_USERNAME
  channel: SLACK_CHANNEL
